# Generated by Django 3.2.8 on 2021-10-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(auto_created=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('type', models.CharField(default='author', max_length=255)),
                ('host', models.URLField(default='http://127.0.0.1:8000/api/', max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(default='http://127.0.0.1:8000/api/', max_length=255)),
                ('github', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author_id', models.IntegerField(editable=False)),
                ('text_content', models.TextField(blank=True)),
                ('image_content', models.ImageField(blank=True, upload_to='')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('public', models.IntegerField(choices=[(0, 'Public')], default='public')),
            ],
        ),
    ]
