# Generated by Django 3.2.8 on 2021-11-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', 'nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
