# Generated by Django 3.2.7 on 2021-10-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(auto_created=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('type', models.CharField(default='author', max_length=255)),
                ('host', models.URLField(default='http://127.0.0.1:8000/', max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(default='http://127.0.0.1:8000/', max_length=255)),
                ('github', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
