# Generated by Django 3.2.8 on 2021-10-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(max_length=255),
        ),
    ]
