# Generated by Django 3.2.8 on 2021-10-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='host',
            field=models.URLField(default='http://127.0.0.1:8000/api/', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.CharField(default='http://127.0.0.1:8000/api/', max_length=255),
        ),
    ]
