# Generated by Django 3.2.8 on 2021-11-25 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_node_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubAccessData',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('last_accessed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
