# Generated by Django 3.2.7 on 2021-10-23 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_post_visibility'),
        ('api', '0002_inbox_model'),
    ]

    operations = [
    ]
