# Generated by Django 3.2.8 on 2021-10-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211013_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_page',
            field=models.CharField(default='garbage', max_length=255),
            preserve_default=False,
        ),
    ]
