# Generated by Django 3.2.8 on 2021-10-24 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_post_image_content'),
        ('api', '0002_alter_post_visibility'),
    ]

    operations = [
    ]
