# Generated by Django 3.2.7 on 2021-10-23 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_0002_alter_post_visibility_0002_inbox_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='author_id',
            new_name='author',
        ),
    ]
