# Generated by Django 3.2.8 on 2021-10-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_github'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author_id', models.IntegerField(editable=False)),
                ('text_content', models.TextField(blank=True)),
                ('image_content', models.ImageField(blank=True, upload_to='')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField()),
            ],
        ),
    ]
