# Generated by Django 3.2.8 on 2021-11-25 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_user_id_githubaccessdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubaccessdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='githubaccessdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
