# Generated by Django 3.2.8 on 2021-10-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='public',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Friend')], default='public'),
        ),
    ]
