# Generated by Django 3.2.8 on 2021-10-26 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.post'),
        ),
        migrations.DeleteModel(
            name='SharedPost',
        ),
    ]
