# Generated by Django 3.2.8 on 2021-10-29 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_20211024_1643'),
        ('api', '0005_add_inbox_created_at'),
    ]

    operations = [
    ]
