# Generated by Django 3.2.8 on 2021-11-25 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211125_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment_page',
            new_name='comments',
        ),
    ]
