# Generated by Django 3.2.8 on 2021-10-28 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_inbox_created_at'),
        ('api', '0005_alter_like_object_id'),
    ]

    operations = [
    ]
