# Generated by Django 3.2.8 on 2021-10-29 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20211027_2304'),
        ('api', '0006_merge_20211028_2023'),
    ]

    operations = [
    ]
