# Generated by Django 3.2.8 on 2021-10-29 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20211028_2112'),
        ('api', '0006_merge_20211028_2132'),
    ]

    operations = [
    ]
