# Generated by Django 3.2.8 on 2021-11-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_node_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='team',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
