# Generated by Django 3.2.8 on 2021-10-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20211028_2119'),
        ('api', '0007_merge_20211028_2315'),
    ]

    operations = [
    ]
