# Generated by Django 3.2.8 on 2021-10-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_post_shared_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_content',
        ),
    ]
