# Generated by Django 3.2.7 on 2021-10-18 04:23

from django.db import migrations, models
from ..models import SiteSetting


def allow_user(apps, schema_editor):
    # automatically seed allow_user setting
    SiteSetting.objects.create_setting(setting="allow_join", on=True)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_update_user_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(max_length=255, unique=True)),
                ('on', models.BooleanField()),
            ],
        ),
        migrations.RunPython(allow_user),
    ]
