# Generated by Django 3.2.8 on 2021-10-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_image_link'),
        ('api', '0008_merge_20211029_1040'),
    ]

    operations = [
    ]
