# Generated by Django 3.2.8 on 2021-10-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_0004_post_image_link_0008_merge_20211029_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
