# Generated by Django 3.2.8 on 2021-10-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_post_image_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='shared_post',
        ),
    ]
