# Generated by Django 3.2.8 on 2021-10-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_allow_image_link_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['published']},
        ),
    ]
