# Generated by Django 3.2.8 on 2021-10-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20211029_1040'),
        ('api', '0013_merge_20211029_1047'),
    ]

    operations = [
    ]
