# Generated by Django 3.2.8 on 2021-10-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_order_comment_by_published'),
        ('api', '0014_merge_20211029_1108'),
    ]

    operations = [
    ]
