# Generated by Django 3.2.8 on 2021-10-29 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_merge_20211029_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shared_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.post'),
        ),
    ]
