# Generated by Django 3.2.8 on 2021-11-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_post_shared_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='object_id',
        ),
        migrations.AddField(
            model_name='inbox',
            name='item',
            field=models.JSONField(default=dict),
        ),
    ]
