# Generated by Django 3.2.8 on 2021-11-22 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_inbox_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inbox',
            options={'ordering': ['-created_at']},
        ),
    ]
