# Generated by Django 3.2.8 on 2021-11-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_node_team'),
        ('api', '0019_node_auth_token'),
    ]

    operations = [
    ]
