# Generated by Django 3.2.8 on 2021-11-30 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_merge_0007_node_team_0019_node_auth_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Node',
        ),
    ]
