# Generated by Django 3.2.8 on 2021-11-30 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_comment_page_post_comments'),
        ('api', '0022_node'),
    ]

    operations = [
    ]
