# Generated by Django 3.2.8 on 2021-12-05 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_post_content_type'),
        ('api', '0024_auto_20211204_1023'),
    ]

    operations = [
    ]
